{
 "title": "Cilium / Overview",
 "description": "Dashboard for Cilium (https://cilium.io/) metrics",
 "tags": [
  "cni",
  "ebpf",
  "cilium-agent",
  "cilium-operator",
  "cilium",
  "portefaix",
  "portefaix-observability"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cilium_version,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(cilium_version{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "pod",
    "query": "label_values(cilium_version, pod)"
   },
   {
    "name": "app",
    "label": "Application",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (cilium_version{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cilium_nodes_all_num{namespace=~\"$namespace\", job=\"$job\", pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cilium_unreachable_nodes{namespace=~\"$namespace\", job=~\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cilium Policies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cilium_policy{k8s_app=\"cilium\", cluster=~\"$cluster\", namespace=~\"$namespace\", pod=~\"$pod\"}) / count(cilium_version)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cilium_endpoint{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cilium Agent Log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$app\", level=~\"$level\"}"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"error\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"warn\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in DEBUG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"debug\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"unknown\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API call latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API call latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_sum{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])/rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "# API calls (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "# API calls (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "API return codes (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} )"
    }
   ]
  },
  {
   "title": "API return codes (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{k8s_app=\"cilium\", pod=~\"$pod\"}[1m])) by (pod, method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}} )"
    }
   ]
  }
 ]
}