{
 "title": "Portefaix / Grafana / Overview",
 "description": "Portefaix / Grafana / Overview",
 "tags": [
  "grafana",
  "observability",
  "portefaix",
  "portefaix-observability"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(grafana_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(grafana_build_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (grafana_build_info{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Grafana"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_folder{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Folders"
    },
    {
     "expr": "grafana_stat_totals_dashboard{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Dashboards"
    },
    {
     "expr": "grafana_stat_total_orgs{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Organizations"
    },
    {
     "expr": "grafana_stat_total_users{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Users"
    },
    {
     "expr": "grafana_stat_active_users{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Active User"
    },
    {
     "expr": "grafana_stat_totals_alert_rules{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Alert rules"
    },
    {
     "expr": "grafana_stat_totals_rule_groups{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Rule groups"
    },
    {
     "expr": "grafana_stat_total_teams{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Teams"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Grafana Log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$app\", level=~\"$level\"}"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"error\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"warn\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in DEBUG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"debug\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"unknown\"} [$__interval]))"
    }
   ]
  },
  { "title": "Grafana API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Grafana API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (method, handler) (rate(grafana_http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\"}[5m]))",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  { "title": "Data Sources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Data Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "grafana_stat_totals_datasource{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{ plugin_id }}"
    }
   ]
  },
  {
   "title": "Plugin QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 37 },
   "targets": [
    {
     "expr": "rate(grafana_plugin_request_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{ plugin_id }}.{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Grafana Plugins",
   "type": "table",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "grafana_plugin_build_info{namespace=\"$namespace\", job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Plugin RT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(grafana_plugin_request_duration_milliseconds_sum{namespace=\"$namespace\", job=\"$job\"}[5m]) /\nincrease(grafana_plugin_request_duration_milliseconds_count{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{ plugin_id }}.{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Data Source QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 47 },
   "targets": [
    {
     "expr": "rate(grafana_datasource_request_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{ datasource }}:{{ method }}:{{ code }}"
    }
   ]
  },
  {
   "title": "Data Source RT",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(grafana_datasource_request_duration_seconds_sum{namespace=\"$namespace\", job=\"$job\"}[5m]) / increase(grafana_datasource_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{ datasource }}{{ datasource }}:{{ method }}:{{ code }}"
    }
   ]
  },
  {
   "title": "Data Source Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(grafana_datasource_response_size_bytes_sum{namespace=\"$namespace\", job=\"$job\"}[5m]) / increase(grafana_datasource_response_size_bytes_count{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "{{ datasource }}{{ datasource }}:{{ method }}:{{ code }}"
    }
   ]
  }
 ]
}