{
 "title": "Portefaix / Observability / SRE",
 "tags": [
  "compute",
  "node-exporter",
  "prometheus",
  "sre",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "job",
    "label": "Category",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "hostname",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "device",
    "label": "device",
    "query": {
     "query": "label_values(node_disk_reads_completed_total, device)"
    }
   },
   {
    "name": "devices",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, device)"
    }
   },
   { "name": "maxmount", "label": "maxmount", "query": { "query": "" } },
   {
    "name": "total",
    "label": "total_servers",
    "query": {
     "query": "query_result(count(node_uname_info{job=~\"$job\"}))"
    }
   },
   {
    "name": "network_interface",
    "label": "network_interface",
    "query": {
     "query": "label_values(node_network_info{operstate=\"up\"}, device)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$instance\",job=\"$job\"}[$interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Root FS Used"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (instance) (node_uname_info{instance=\"$instance\"})",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU% Basic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "IOWait"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=\"$instance\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\"} - node_boot_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Core",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load avg",
   "type": "stat",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu))",
     "legendFormat": "1 min"
    },
    {
     "expr": "avg(node_load5{instance=\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu)) ",
     "legendFormat": "5 min"
    },
    {
     "expr": "avg(node_load15{instance=\"$instance\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"$job\"}) by (cpu)) ",
     "legendFormat": "15 min"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$instance\",job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instan\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$instance\",job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$instance\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "RAM info",
   "type": "stat",
   "description": "Node Memory info",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(node_memory_MemTotal_bytes{instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Total GB"
    },
    {
     "expr": "ceil(node_memory_MemFree_bytes{instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Available GB"
    },
    {
     "expr": "(ceil(node_memory_MemTotal_bytes{instance=\"$instance\"}/(1024*1024))/1024)-(ceil(node_memory_MemFree_bytes{instance=\"$instance\"})/(1024*1024))/1024",
     "legendFormat": "Used GB"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",job=\"$job\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"$instance\",job=\"$job\",device!~'rootfs'}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "ROOT FILESYSTEM",
   "type": "stat",
   "description": "device=\"/dev/root\n",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(node_filesystem_size_bytes{device=~\"/dev/mmcblk.*|/dev/sda.*\",instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Total GB"
    },
    {
     "expr": "ceil(node_filesystem_avail_bytes{device=~\"/dev/mmcblk.*|/dev/sda.*\",instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Available GB"
    },
    {
     "expr": "ceil(node_filesystem_size_bytes{device=~\"/dev/mmcblk.*|/dev/sda.*\",instance=\"$instance\"}/(1024*1024))/1024-ceil(node_filesystem_avail_bytes{device=~\"/dev/mmcblk.*|/dev/sda.*\",instance=\"$instance\"}/(1024*1024))/1024",
     "legendFormat": "Used GB"
    }
   ]
  },
  { "title": "Investigative metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network received and transmit",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}}  receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{ instance=\"$instance\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\",job=\"$job\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\",job=\"$job\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=\"$instance\",job=\"$job\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\",job=\"$job\",device=~\"$device\"}[$interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Free inodes:$maxmount ",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_filesystem_files_free{instance=~\"$instance\",fstype=~\"ext.?|xfs\"})"
    }
   ]
  },
  {
   "title": "Network Traffic Out",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{device=\"$network_interface\",instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Network Traffic In",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{device=\"$network_interface\",instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Hardware Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~'$instance'}",
     "legendFormat": "{{instance}}_{{chip}}_{{sensor}}"
    }
   ]
  }
 ]
}