{
 "title": "Portefaix / Prometheus Operator / Overview",
 "tags": [
  "prometheus",
  "operator",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(prometheus_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(prometheus_operator_build_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (prometheus_operator_build_info{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_managed_resources{job=\"$job\", state=\"selected\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_managed_resources{job=\"$job\", state=\"rejected\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Operator logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", job=\"$namespace/$job\"}"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"error\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"warn\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in DEBUG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"debug\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"unknown\"} [$__interval]))"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "List Operations failures",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_operator_list_operations_failed_total{job=\"$job\"}",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Watch Operations failures",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_operator_watch_operations_failed_total{job=\"$job\"}",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Reconcile errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_reconcile_errors_total",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_alertmanager_config_validation_errors_total{job=\"$job\"}",
     "legendFormat": "Alertmanager config validation errors"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_rule_validation_errors_total{job=\"$job\"}",
     "legendFormat": "Rules validation errors"
    }
   ]
  },
  { "title": "Operational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Operator API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(prometheus_operator_kubernetes_client_http_request_duration_seconds_count{job=\"$job\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Reconciliation QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(prometheus_operator_reconcile_duration_seconds_count{job=\"$job\"}[5m]))",
     "legendFormat": "{{ controller }}"
    }
   ]
  }
 ]
}