{
 "title": "Portefaix / Tempo / Overview",
 "tags": [
  "tracing",
  "observability",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tempo_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(tempo_build_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (tempo_build_info{namespace=\"$namespace\", job=~\"$namespace/.+\", pod=~\"tempo-.+\"})",
     "legendFormat": "Loki"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Tempo logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$app\", level=~\"$level\"}"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"error\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"warn\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in DEBUG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"debug\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"unknown\"} [$__interval]))"
    }
   ]
  },
  { "title": "Tempo API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Tempo API Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tempo_request_duration_seconds_bucket{namespace=\"$namespace\", job=~\"$namespace/.+\", pod=~\"tempo-.+\"}[5m])) by (le,route))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Received  Span/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(tempo_distributor_spans_received_total{namespace=\"$namespace\", service=~\"tempo-.+\"}[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Received bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_bytes_received_total{namespace=\"$namespace\", service=~\"tempo-.+\"}[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "Distributor Batchs/s",
   "type": "timeseries",
   "description": "Batch appends sent to ingesters / sec",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tempo_distributor_ingester_appends_total{namespace=\"$namespace\", service=~\"tempo-.+\"}[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "rate(tempo_distributor_ingester_append_failures_total{namespace=\"$namespace\", service=~\"tempo-.+\"}[5m])",
     "legendFormat": "failed"
    }
   ]
  }
 ]
}