{
 "title": "Node Exporter / Node CPU and System",
 "tags": [
  "prometheus",
  "node-exporter",
  "linux-node-integration"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info{sysname!=\"Darwin\", job=\"node-exporter\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\", job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "Total CPU utilisation percent.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count by (instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))) \n- \navg by (instance) (sum by (instance, mode)(irate(node_cpu_seconds_total{mode='idle',job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])))) * 100) \n/ \ncount by(instance) (count(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}) by (cpu, instance))\n"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total CPU utilisation percent.",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=~\"idle|iowait|steal\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})\n) * 100\n",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "System: Processes executing in kernel mode.\nUser: Normal processes executing in user mode.\nNice: Niced processes executing in user mode.\nIdle: Waiting for something to happen.\nIowait: Waiting for I/O to complete.\nIrq: Servicing interrupts.\nSoftirq: Servicing softirqs.\nSteal: Time spent in other operating systems when running in a virtualized environment.\n",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, mode) (irate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])) \n/ on(instance) \ngroup_left sum by (instance)((irate(node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))) * 100\n",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "description": "System load average over the previous 1, 5, and 15 minute ranges. A measurement of how many processes are waiting for CPU cycles. The maximum number is the number of CPU cores for the node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_load1{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "1m load average"
    },
    {
     "expr": "avg by (instance) (node_load5{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "5m load average"
    },
    {
     "expr": "avg by (instance) (node_load15{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count by (instance) (node_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Context Switches / Interrupts",
   "type": "timeseries",
   "description": "Context switches occur when the operating system switches from running one process to another.\nInterrupts are signals sent to the CPU by external devices to request its attention.\n\nA high number of context switches or interrupts can indicate that the system is overloaded or that there are problems with specific devices or processes.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(node_intr_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timezone",
   "type": "stat",
   "description": "Timezone set on instance.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_zone_offset_seconds{job=~\"$job\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Time Synchronized Status",
   "type": "status-history",
   "description": "Status of time synchronization.",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_timex_sync_status{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Sync status"
    }
   ]
  },
  {
   "title": "Time Synchronized Drift",
   "type": "timeseries",
   "description": "Time synchronization is essential to ensure accurate timekeeping, which is critical for many system operations such as logging, authentication, and network communication, as well as distributed systems or clusters where data consistency is important.\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_offset_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Time offset in between local system and reference clock"
    },
    {
     "expr": "node_timex_maxerror_seconds{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Maximum error in seconds"
    }
   ]
  }
 ]
}