{
 "title": "Portefaix / Cloudflare Tunnel / Overview",
 "tags": [
  "portefaix",
  "portefaix-observability",
  "zero-trust",
  "cloudflared",
  "cloudflare"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(build_info{container=\"cloudflare-tunnel\"},namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(build_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (build_info{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cloudflared_config_local_config_pushes_errors{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Config errors"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(promhttp_metric_handler_requests_total{namespace=\"$namespace\", job=\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Dex Log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"error\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"warn.*\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in DEBUG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"debug\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"unknown\"} [$__interval]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(cloudflared_tunnel_total_requests{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(cloudflared_tunnel_request_errors{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "description": "Concurrent requests proxied through each tunnel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}