{
 "title": "Portefaix / Prometheus Operator / Overview",
 "tags": [
  "prometheus",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(prometheus_operator_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(prometheus_operator_build_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (prometheus_operator_build_info{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_managed_resources{namespace=\"$namespace\", job=\"$job\", state=\"selected\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_managed_resources{namespace=\"$namespace\", job=\"$job\", state=\"rejected\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Operator logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", job=\"$namespace/$job\"}"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$namespace/$job\", level=\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$namespace/$job\", level=\"warn\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$namespace/$job\", level=\"error\"} [$__interval]))"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "List Operations failures",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_operator_list_operations_failed_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Watch Operations failures",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_operator_watch_operations_failed_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Reconcile errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_reconcile_errors_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_alertmanager_config_validation_errors_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Alertmanager config validation errors"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_rule_validation_errors_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Rules validation errors"
    }
   ]
  },
  { "title": "Operational", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Operator API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(prometheus_operator_kubernetes_client_http_request_duration_seconds_count{namespace=\"$namespace\", job=\"$job\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Reconciliation QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(prometheus_operator_reconcile_duration_seconds_count{namespace=\"$namespace\", job=\"$job\"}[5m]))",
     "legendFormat": "{{ controller }}"
    }
   ]
  }
 ]
}