# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
ingress:
  enabled: false

kargo:
  global:
    labels:
      portefaix.xyz/version: v1.3.0

  api:
    logLevel: INFO

  # oidc:
  #   enabled: true
  #   connectors:
  #   - id: github
  #     name: GitHub
  #     type: github
  #     config:
  #       clientID: <your client ID>
  #       clientSecret: <your client secret>
  #       redirectURI: <http(s)>://<api.host>/dex/callback

  controller:
    argocd:
      namespace: gitops
    logLevel: INFO

  managementController:
    logLevel: INFO

  webhooksServer:
    logLevel: INFO

  garbageCollector:
    logLevel: INFO

