{
 "title": "Keptn Lifecycle Controller / Workloads",
 "tags": [
  "gitops",
  "workloads",
  "klc",
  "keptn"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Workload",
    "query": {
     "query": "label_values(keptn_deployment_workload_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Succeeded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(keptn_deployment_count{keptn_deployment_workload_name=\"$Workload\", keptn_deployment_workload_status=\"Succeeded\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time between Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion, keptn_deployment_workload_version) (keptn_deployment_deploymentinterval{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(keptn_deployment_count{keptn_deployment_workload_name=\"$Workload\", keptn_deployment_workload_status=\"Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Time",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(keptn_deployment_workload_version) (keptn_deployment_deploymentduration{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "{{keptn_workload_version}}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(keptn_deployment_active{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time between Deployments",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(keptn_deployment_workload_previousversion, keptn_deployment_workload_version) (keptn_deployment_deploymentinterval{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "{{keptn_deployment_workload_previousversion}} - {{keptn_deployment_workload_version}}"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "operation": "$Workload/WorkloadPreDeployTasks",
     "service": "keptn-lifecycle-operator"
    }
   ]
  },
  {
   "title": "Deployments Active",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "max(keptn_deployment_active{keptn_deployment_workload_name=\"$Workload\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}