# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
loki:
  clusterLabelOverride: portefaix-staging-eks
  loki:
    storage:
      bucketNames:
        admin: portefaix-homelab-logs-admin
        chunks: portefaix-homelab-logs-chunks
        ruler: portefaix-homelab-logs-ruler
      type: s3
      s3:
        s3: null
        endpoint: ${AWS_S3_ENDPOINT}


ack:
  enabled: true
  clusterName: portefaix-staging-eks
  serviceAccount: loki
  tags:
    portefaix/krm: aws-controllers-k8s
    portefaix/environment: staging
