# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
loki:
  clusterLabelOverride: portefaix-staging-eks
  loki:
    storage:
      bucketNames:
        admin: portefaix-homelab-logs-admin
        chunks: portefaix-homelab-logs-chunks
        ruler: portefaix-homelab-logs-ruler
      type: s3
      s3:
        s3: null
        endpoint: ${AWS_S3_ENDPOINT}


  indexGateway:
    resources:
      limits:
        memory: 600Mi
      requests:
        cpu: 60m
        memory: 200Mi

  ruler:
    resources:
      limits:
        memory: 600Mi
      requests:
        cpu: 60m
        memory: 200Mi

ack:
  enabled: true
  clusterName: portefaix-staging-eks
  serviceAccount: loki
  tags:
    - key: portefaix/krm
      value: aws-controllers-k8s
    - key: portefaix/environment
      value: staging
