{
 "title": "DORA / Overview",
 "description": "DORA metrics are scraped using the OpenTelemetry GitHub Receiver.",
 "tags": [
  "opentelemetry",
  "github",
  "dora"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   {
    "name": "organization",
    "label": "organization",
    "query": {
     "query": "label_values(organization_name)"
    }
   },
   {
    "name": "team",
    "label": "team",
    "query": {
     "query": "label_values({organization_name=\"$organization\"},team_name)"
    }
   },
   { "name": "repo", "label": "repo", "query": { "query": "label_values(repository_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Trunk Based Development",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Branch Age (Days)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(repository_name) (vcs_repository_ref_time_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
       "legendFormat": "{{repository_name}}"
      }
     ]
    },
    {
     "title": "Average Branch Age (Days)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "targets": [
      {
       "expr": "avg by(repository_name, ref_name) (vcs_repository_ref_time_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
       "legendFormat": "{{repository_name}}/{{ref_name}}"
      }
     ]
    },
    {
     "title": "Average branch",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(repository_name) (vcs_repository_ref_count{repository_name=~\"$repo\", team_name=~\"$team\"})",
       "legendFormat": "{{repository_name}}"
      }
     ]
    },
    {
     "title": "Open Branches",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 8 },
     "targets": [
      {
       "expr": "avg by(repository_name) (vcs_repository_ref_count{repository_name=~\"$repo\", team_name=~\"$team\"} > 1)",
       "legendFormat": "{{repository_name}}"
      }
     ]
    },
    {
     "title": "Open Pull Request Duration (Days)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(repository_name) (vcs_repository_change_time_open_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
       "legendFormat": "{{repository_name}}"
      }
     ]
    },
    {
     "title": "Open Pull Request Age",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "vcs_repository_change_time_open_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}",
       "legendFormat": "{{repository_name}}/{{ref_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Detailed Git Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Average Branch Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "branches" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(avg (vcs_repository_ref_count{repository_name=~\"$repo\", team_name=~\"$team\"} > 1))",
     "legendFormat": "{{organization_name}}"
    }
   ]
  },
  {
   "title": "Average Branch Age Per Repo In Days",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(repository_name) (vcs_repository_ref_time_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}) / 86400",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "vcs_repository_ref_count{repository_name=~\"$repo\", team_name=~\"$team\"} - 1",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Branch Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_repository_ref_time_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{repository_name}}/{{ref_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "vcs_repository_change_count{change_state=\"open\", repository_name=~\"$repo\"}",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Open Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_repository_change_time_open_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{repository_name}}/{{ref_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "vcs_repository_change_count{change_state=\"merged\", repository_name=~\"$repo\"}",
     "legendFormat": "{{repository_name}}"
    }
   ]
  },
  {
   "title": "Merged Pull Request Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vcs_repository_change_time_to_merge_seconds{repository_name=~\"$repo\", team_name=~\"$team\"}",
     "legendFormat": "{{repository_name}}/{{ref_name}}"
    }
   ]
  },
  {
   "title": "Build In Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Vulnerabilities (CVEs)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(cve_severity) (git_repository_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", repository_name=~\"$repo\", cve_severity=\"critical\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vulnerabilities by Repo",
     "type": "bargauge",
     "gridPos": { "h": 14, "w": 17, "x": 7, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(repository_name) (git_repository_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", repository_name=~\"$repo\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "High Vulnerabilities (CVEs)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(cve_severity) (git_repository_cve_count{organization_name=~\"$organization\", team_name=~\"$team\", repository_name=~\"$repo\", cve_severity=\"high\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}