# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

[formatting]
align_entries = false
align_comments = true
align_single_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
compact_entries = false
column_width = 100
indent_tables = false
indent_entries = false
indent_string = "  "
trailing_newline = true
reorder_keys = false
reorder_arrays = false
allowed_blank_lines = 1
crlf = false
