# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

formatter:
  type: basic
  indentless_arrays: true
  retain_line_breaks_single: true
