{
 "title": "Qdrant test",
 "tags": [
  "db",
  "qdrant"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(app_info{name=\"qdrant\"},job)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(app_info{name=\"qdrant\", job=~\"$job\"},namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(app_info{namespace=~\"$namespace\", name=\"qdrant\", job=~\"$job\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Qdrant Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "app_info{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Term",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cluster_term{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_voter{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(cluster_peers_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cluster_pending_operations_total{job=~\"$job\", namespace=~\"$namespace\", pod=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Collections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(collections_total{namespace=~\"$namespace\", pod=~\"$instance\"}) by (namespace, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Vectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(collections_vector_total{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  { "title": "REST Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rest_responses_avg_duration_seconds{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "avg - {{namespace}} / {{pod}}"
    },
    {
     "expr": "avg(rest_responses_min_duration_seconds{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "min - {{namespace}} / {{pod}}"
    },
    {
     "expr": "avg(rest_responses_max_duration_seconds{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "max - {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(rest_responses_total{namespace=~\"$namespace\", pod=~\"$instance\"}[$__rate_interval])) by(namespace, pod)",
     "legendFormat": "total - {{namespace}}  / {{pod}}"
    },
    {
     "expr": "sum(rate(rest_responses_fail_total{namespace=~\"$namespace\", pod=~\"$instance\"}[$__rate_interval])) by(namespace, pod)",
     "legendFormat": "failed - {{namespace}}  / {{pod}}"
    }
   ]
  },
  { "title": "gRPC Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(grpc_responses_avg_duration_seconds{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "avg - {{namespace}} / {{pod}}"
    },
    {
     "expr": "avg(grpc_responses_min_duration_seconds{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "min - {{namespace}} / {{pod}}"
    },
    {
     "expr": "avg(grpc_responses_max_duration_seconds{namespace=~\"$namespace\", pod=~\"$instance\"}) by(namespace, pod)",
     "legendFormat": "max - {{namespace}} / {{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_responses_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by(namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "total | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(rate(grpc_responses_fail_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by(namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "failed | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  }
 ]
}