{
 "title": "Keptn Lifecycle Controller / Metrics",
 "tags": [
  "keptn",
  "klt",
  "keptn-lifecycle-toolkit",
  "gitops"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_task_active{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_evaluation_active{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_task_count{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Evaluations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_evaluation_count_total{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(le) (keptn_task_duration_bucket{job=\"otel-collector\", le!=\"+Inf\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Evaluation Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(le) (keptn_evaluation_duration_bucket{job=\"otel-collector\", le!=\"+Inf\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Active Deployments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_deployment_active{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finished Deployments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(job) (keptn_deployment_count{job=\"otel-collector\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Duration Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(le) (keptn_deployment_duration_bucket{job=\"otel-collector\", le!=\"+Inf\"}))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}