{
 "title": "Logging / Applications overview",
 "tags": [
  "loki",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Repartition",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (rate({container=~\".+\"}[5m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Number of lines / 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum(rate({container=~\".+\"}[5m])) by (container))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Repartition",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (container) (count_over_time({namespace=~\".+\"} |= \"error\" [5m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Number of errors / 5m",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\".+\"} |= \"error\" [5m])) by (container)",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}