{
 "title": "Logging / Applications",
 "description": "Logs for applications",
 "tags": [
  "logs",
  "loki",
  "portefaix-logs",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "label": "Datasource", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "app",
    "label": "Application",
    "query": {}
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\"})[$__interval]))",
     "legendFormat": "log rate"
    }
   ]
  },
  {
   "title": "Searched Logs per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({app=\"$app\"} |~ \"$search\")[$__interval]))",
     "legendFormat": "log rate"
    }
   ]
  },
  {
   "title": "Recent Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"$app\"} |~ \"$search\""
    }
   ]
  }
 ]
}