# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.ack.enabled -}}
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Policy
metadata:
  labels:
    {{- include "loki.labels" (index $.Subcharts "loki") | nindent 4 }}
    app.kubernetes.io/component: iam
    portefaix.xyz/krm: ack
    portefaix.xyz/version: v1.3.0
  name: {{ .Values.ack.clusterName }}-loki-s3
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.ack.clusterName }}-loki-s3
  description: "Bucket permissions for Loki"
  policyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket"
          ],
          "Resource": [
            "arn:aws:s3:::{{ .Values.ack.clusterName }}-loki-admin",
            "arn:aws:s3:::{{ .Values.ack.clusterName }}-loki-chunks",
            "arn:aws:s3:::{{ .Values.ack.clusterName }}-loki-ruler"
          ]
        },
        {
          "Effect": "Allow",
          "Action": [
            "s3:GetObject",
            "s3:DeleteObject",
            "s3:PutObject"
          ],
          "Resource": [
            "arn:aws:s3:::{{ .Values.ack.clusterName }}-loki-admin/*",
            "arn:aws:s3:::{{ .Values.ack.clusterName }}-loki-chunks/*",
            "arn:aws:s3:::{{ .Values.ack.clusterName }}-loki-ruler/*"
          ]
        }
      ]
    }
  tags:
    {{- toYaml .Values.ack.tags | nindent 4 }}
{{- end }}
