# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.ack.enabled -}}
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: Role
metadata:
  labels:
    {{- include "loki.labels" (index $.Subcharts "loki") | nindent 4 }}
    app.kubernetes.io/component: iam
    portefaix.xyz/krm: ack
    portefaix.xyz/version: v1.3.0
  name: {{ .Values.ack.clusterName }}-loki
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.ack.clusterName }}-loki
  assumeRolePolicyDocument: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Principal": {
            "Service": "pods.eks.amazonaws.com"
          },
          "Action": [
            "sts:AssumeRole",
            "sts:TagSession"
          ]
        }
      ]
    }
  policyRefs:
    - name: {{ .Values.ack.clusterName }}-loki-s3
  tags:
    {{- toYaml .Values.ack.tags | nindent 4 }}
{{- end }}
