# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.ack.enabled -}}
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  labels:
    {{- include "loki.labels" (index $.Subcharts "loki") | nindent 4 }}
    app.kubernetes.io/component: iam
    portefaix.xyz/krm: ack
    portefaix.xyz/version: v1.3.0
  name: {{ .Values.ack.clusterName }}-loki
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.ack.clusterName }}
  namespace: {{ .Release.Namespace }}
  serviceAccount: {{ .Values.ack.serviceAccount }}
  roleRef:
    name: {{ .Values.ack.clusterName }}-loki
  tags:
    {{- toYaml .Values.ack.tags | nindent 4 }}
{{- end }}
