# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.crossplaneCloudflare.enabled -}}
{{- $accountId := .Values.crossplaneCloudflare.accountId -}}
{{- $region := .Values.crossplaneCloudflare.region -}}
{{- range $bucket := (list "admin" "chunks" "ruler") }}
---
apiVersion: r2.cloudflare.crossplane.io/v1alpha1
kind: R2Bucket
metadata:
  labels:
    {{- include "loki.labels" (index $.Subcharts "loki") | nindent 4 }}
    app.kubernetes.io/component: bucket
    portefaix.xyz/krm: cloudflare
    portefaix.xyz/version: v1.3.0
  name: {{ $.Release.Name }}-loki-{{ $bucket }}
  namespace: {{ $.Release.Namespace }}
spec:
  forProvider:
    accountId: {{ $accountId | quote }}
    name: {{ $.Values.crossplaneCloudflare.bucketName }}-loki-{{ $bucket }}
    location: {{ $region }}
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
