# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.crossplaneScaleway.enabled -}}
{{- $providerName := required "crossplaneScaleway.provider.name is required when crossplaneScaleway.enabled is true" .Values.crossplaneScaleway.provider.name -}}
---
apiVersion: iam.scaleway.m.upbound.io/v1alpha1
kind: Application
metadata:
  labels:
    {{- include "loki.labels" (index $.Subcharts "loki") | nindent 4 }}
    app.kubernetes.io/component: iam
    portefaix.xyz/krm: crossplane
    portefaix.xyz/version: v1.3.0
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    name: {{ .Release.Name }}-loki
    description: "IAM application for Loki Object Storage"
  providerConfigRef:
    name: {{ $providerName }}
---
apiVersion: iam.scaleway.m.upbound.io/v1alpha1
kind: Policy
metadata:
  labels:
    {{- include "loki.labels" (index $.Subcharts "loki") | nindent 4 }}
    app.kubernetes.io/component: iam
    portefaix.xyz/krm: crossplane
    portefaix.xyz/version: v1.3.0
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
spec:
  forProvider:
    name: {{ .Release.Name }}-loki
    description: "Policy for Loki Object Storage access"
    applicationIdRef:
      name: {{ .Release.Name }}-loki
    rule:
    - permissionSetNames:
      - ObjectStorageFullAccess
  providerConfigRef:
    name: {{ $providerName }}
