# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.crossplaneExoscale.enabled -}}
{{- range $bucket := (list "admin" "chunks" "ruler") }}
---
apiVersion: sos.sos.exoscale.ch/v1alpha1
kind: Bucket
metadata:
  name: {{ $.Values.crossplaneExoscale.bucketName }}-loki-{{ $bucket }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    crossplane.io/external-name: {{ $.Values.crossplaneExoscale.bucketName }}-loki-{{ $bucket }}
spec:
  forProvider: {}
  providerConfigRef:
    kind: ClusterProviderConfig
    name: {{ $.Values.crossplaneExoscale.provider.name }}
---
apiVersion: sos.sos.m.exoscale.ch/v1alpha1
kind: BucketVersioning
metadata:
  annotations:
    meta.upbound.io/example-id: sos/v1alpha1/bucketversioning
  labels:
    testing.upbound.io/example-name: versioning_example
  name: {{ $.Values.crossplaneExoscale.bucketName }}-loki-{{ $bucket }}
  namespace: {{ $.Release.Namespace }}
spec:
  forProvider:
    bucketRef:
      name: {{ $.Values.crossplaneExoscale.bucketName }}-loki-{{ $bucket }}
      namespace: {{ $.Release.Namespace }}
    versioningConfiguration:
    - status: Enabled
  providerConfigRef:
    kind: ClusterProviderConfig
    name: {{ $.Values.crossplaneExoscale.provider.name }}
{{- end }}
{{- end }}
