{
 "title": "OpenCost / Namespace",
 "description": "A dashboard that monitors OpenCost and focuses on namespace costs. It is created using the [opencost-mixin](https://github.com/adinhodovic/opencost-mixin).",
 "tags": [
  "opencost",
  "opencost-mixin"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opencost_build_info, job)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   }
  ]
 },
 "panels": [
  { "title": " Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hourly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 1)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 1)\n  )\n) by (namespace)\n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 24)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 24)\n  )\n) by (namespace)\n"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n  )\n) by (namespace)\n"
    }
   ]
  },
  {
   "title": "Monthly CPU Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n)\n"
    }
   ]
  },
  {
   "title": "Monthly Ram Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n)\n"
    }
   ]
  },
  {
   "title": "Monthly PV Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) * 730\n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 24)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 24)\n  )\n) by (namespace)\n",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  (\n    sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n  )\n  +\n  (\n    sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n    by (namespace, instance)\n    * on(instance) group_left()\n    (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n  )\n) by (namespace)\n",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Cost by Resource",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(container_cpu_allocation{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n)\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n  sum(container_memory_allocation_bytes{job=~\"$job\", namespace=~\"$namespace\"})\n  by (namespace, instance)\n  * on(instance) group_left()\n  (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n)\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) * 730\n",
     "legendFormat": "PV"
    }
   ]
  },
  { "title": "Pod Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pod Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (pod)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 7d) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 7d) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 30d) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 30d) by (instance) * 730)\n    )\n  ) by (pod)\n)\n\n* 100\n- 100\n"
    }
   ]
  },
  {
   "title": "Cost by Pod",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, pod)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (pod)\n)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "Container Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Container Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (container)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (container)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 7d) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 7d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 7d) by (instance) * 730)\n    )\n  ) by (container)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (container)\n)\n\n/\ntopk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"} offset 30d) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"} offset 30d)\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"} offset 30d) by (instance) * 730)\n    )\n  ) by (container)\n)\n\n* 100\n- 100\n"
    }
   ]
  },
  {
   "title": "Cost by Container",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    (\n      sum(container_memory_allocation_bytes{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_ram_hourly_cost{job=~\"$job\"}) by (instance) / (1024 * 1024 * 1024) * 730)\n    )\n    +\n    (\n      sum(container_cpu_allocation{namespace=~\"$namespace\", job=~\"$job\"})\n      by (instance, container)\n      * on(instance) group_left()\n      (avg(node_cpu_hourly_cost{job=~\"$job\"}) by (instance) * 730)\n    )\n  ) by (container)\n)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "PV Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Persistent Volumes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_persistentvolume_capacity_bytes{job=~\"$job\"} / (1024 * 1024 * 1024))\n  by (persistentvolume)\n  * on(persistentvolume) group_left(namespace)\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  * sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n) by (persistentvolume) * 730\n"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) by (persistentvolume) * 730\n"
    }
   ]
  },
  {
   "title": "Cost by PV",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{job=~\"$job\"}\n    / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  *\n  sum(pv_hourly_cost{job=~\"$job\"}) by (persistentvolume)\n  * on(persistentvolume) group_left(namespace) (\n    label_replace(\n      kube_persistentvolumeclaim_info{job=~\"$job\", namespace=~\"$namespace\"},\n      \"persistentvolume\", \"$1\",\n      \"volumename\", \"(.*)\"\n    )\n  )\n) by (persistentvolume) * 730\n",
     "legendFormat": "{{ persistentvolume }}"
    }
   ]
  }
 ]
}