{
 "title": "Beyla / Overview",
 "tags": [
  "opentelemetry",
  "beyla",
  "ebpf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(beyla_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(beyla_build_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Application",
    "query": {}
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (beyla_build_info{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Grafana Agent"
    }
   ]
  },
  {
   "title": "DaemonSet: Running pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_daemonset_status_number_ready{namespace=\"$namespace\", job=\"kube-state-metrics\", daemonset=\"beyla\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL metric exports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (beyla_otel_metric_exports_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OTEL trace exports",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster) (beyla_otel_trace_exports_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Discovered Processes",
   "type": "table",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(process_name) (beyla_instrumented_processes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{job=\"default/beyla\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(process_command) (process_cpu_utilization_ratio{job=\"default/beyla\"})",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Logs",
     "type": "logs",
     "gridPos": { "h": 20, "w": 21, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=\"$app\"} | logfmt"
      }
     ]
    },
    {
     "title": "Logs in ERROR",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$job\", level=\"error\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in WARN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"warn.*\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in INFO",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"info\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in DEBUG",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"debug\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in UNKNOWN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"unknown\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "BPF Logs",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "{namespace=\"opentelemetry\", app=\"beyla\"} | logfmt | component=`BPFLogger`"
      }
     ]
    },
    {
     "title": "Application Errors",
     "type": "logs",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", app=\"beyla\"} |= `ERROR`"
      }
     ]
    }
   ]
  }
 ]
}