# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v2
type: application
name: crossplane
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: crossplane
  # See: https://github.com/crossplane/crossplane/issues/6707
  repository: oci://ghcr.io/home-operations/charts-mirror
  version: 2.3.2
