# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
crossplane:
  resourcesCrossplane:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"

  resourcesRBACManager:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      memory: "512Mi"

  # provider-scaleway: https://github.com/scaleway/crossplane-provider-scaleway
  provider:
    packages:
    - xpkg.upbound.io/scaleway/provider-scaleway:latest
