# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
crossplane:
  resourcesCrossplane:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      memory: "256Mi"

  resourcesRBACManager:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      memory: "256Mi"
