# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.crossplaneCloudflare.enabled -}}
{{- $accountId := .Values.crossplaneCloudflare.accountId -}}
{{- $retention := mul .Values.crossplaneCloudflare.retention 86400 -}}
{{- range $bucket := (list "traces" "admin" "wal") }}
---
apiVersion: r2.cloudflare.crossplane.io/v1alpha1
kind: R2BucketLifecycle
metadata:
  name: {{ $.Release.Name }}-tempo-{{ $bucket }}-lifecycle
  namespace: {{ $.Release.Namespace }}
spec:
  forProvider:
    accountId: {{ $accountId | quote }}
    bucketName: {{ $.Values.crossplaneCloudflare.bucketName }}-tempo-{{ $bucket }}
    rules:
      - id: "expire-tempo-{{ $bucket }}"
        enabled: true
        deleteObjectsTransition:
          condition:
            maxAge: {{ $retention }}
            type: "Age"
  providerConfigRef:
    name: default
{{- end }}
{{- end }}
