{
 "title": "etcd",
 "tags": [ "shancor" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Leader",
   "type": "stat",
   "description": "Do we have a leader?",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(etcd_server_is_leader) by (instance) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leader changes",
   "type": "stat",
   "description": "High value point to etcd being unstable",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_leader_changes_seen_total)",
     "legendFormat": "Lifetime"
    }
   ]
  },
  {
   "title": "Max Database Usage",
   "type": "stat",
   "description": "Database will lock at 95%. Normally in 4GB or 8GB settings.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max without (kubernetes_node, instance, pod)(etcd_mvcc_db_total_size_in_bytes) / max without (kubernetes_node, instance, pod)(etcd_server_quota_backend_bytes)) * 100"
    }
   ]
  },
  {
   "title": "How Much Can Be Defragmented",
   "type": "stat",
   "description": "DB size in MB that can be reduced after defragmentation",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(kubernetes_node, instance, pod)(etcd_mvcc_db_total_size_in_bytes - etcd_mvcc_db_total_size_in_use_in_bytes)"
    }
   ]
  },
  {
   "title": "Compacted Keys",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_debugging_mvcc_db_compaction_keys_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Keys Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_debugging_mvcc_keys_total)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proposals Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(kubernetes_node, instance, pod)(increase(etcd_server_proposals_pending[2m]))",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Write Ahead Log Latency",
   "type": "heatmap",
   "description": "Should be less than 10ms. Use low latency direct NVMe drives vs. network. Warning - IOPS is not a factor in this number!",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max without (kubernetes_node, instance, pod)(increase(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "network round trip heatmap",
   "type": "heatmap",
   "description": "Looking for networking issues between etcd nodes",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(increase(etcd_network_peer_round_trip_time_seconds_bucket[$__rate_interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backend Commit Duration",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max without (instance, kubernetes_node, pod)(increase(etcd_disk_backend_commit_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backend Snapshot Duration",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max without (instance,kubernetes_node)(increase(etcd_disk_backend_snapshot_duration_seconds_bucket[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slow Apply",
   "type": "timeseries",
   "description": "Writing data is Slow (over 100ms)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(etcd_server_slow_apply_total[$__rate_interval])) without (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow Watcher",
   "type": "timeseries",
   "description": "Writing data is Slow (over 100ms)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(etcd_debugging_mvcc_slow_watcher_total[$__rate_interval])) without (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slow Follower Read",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(etcd_server_slow_read_indexes_total[$__rate_interval])) without (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Proposals Failed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(etcd_server_proposals_failed_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Heartbeat and Health Failures",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(etcd_server_heartbeat_send_failures_total[$__rate_interval])",
     "legendFormat": "Heartbeat Failures - {{instance}}"
    },
    {
     "expr": "increase(etcd_server_health_failures[$__rate_interval])",
     "legendFormat": "Health Failures {{instance}}"
    }
   ]
  },
  {
   "title": "Backend Defrag Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "max without (instance, kubernetes_node, pod)(increase(etcd_disk_backend_defrag_duration_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Grpc Server Handling",
   "type": "heatmap",
   "description": "various scenarios like leader election failure",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "max(rate(grpc_server_handling_seconds_bucket{job=~\".*etcd.*\", grpc_type=\"unary\"}[$__rate_interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}