{
 "title": "KCM",
 "tags": [ "shancor" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(job_controller_rate_limiter_use, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Workqueue -  Work Duration",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max without (instance, name)(increase(workqueue_work_duration_seconds_bucket{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workqueue - Queue Duration",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max without(name,instance)(increase(workqueue_queue_duration_seconds_bucket{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Workqueue Adds ",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(3, max without(instance)(increase(workqueue_adds_total{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Retries",
   "type": "barchart",
   "description": "Five Minute Max",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(4, (max without(instance)(increase(workqueue_retries_total{job=\"$job\"}[$__rate_interval]))))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "workqueue_depth",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(3, max without(instance)(max_over_time(workqueue_depth{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Workqueue Unfinished Work",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, max without(instance)(increase(workqueue_unfinished_work_seconds{job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Request Rate - per min",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"2..\"}[$__rate_interval]))",
     "legendFormat": "2xx per sec"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"4..\"}[$__rate_interval]))",
     "legendFormat": "4xx per sec"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "5xx per sec"
    }
   ]
  },
  {
   "title": "cloudprovider aws  avg duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cloudprovider_aws_api_request_duration_seconds_sum{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{request}}"
    }
   ]
  }
 ]
}