{
 "title": "CPU Troubleshooter V1.0.1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_cpu_seconds_total,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total,  instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Current Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", job=\"$job\", instance=\"$instance:9100\"}[1m])) * 100 ",
     "legendFormat": "CPU - {{cpu}}"
    }
   ]
  },
  {
   "title": "Per Core Heat Map - Rate",
   "type": "status-history",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{instance=\"$instance:9100\", mode=\"idle\", job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "core {{cpu}}"
    }
   ]
  },
  {
   "title": "Processes Waiting for CPU",
   "type": "timeseries",
   "description": "more processes to be run than CPU time available to handle them",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_schedstat_waiting_seconds_total{job=\"$job\", instance=~\"$instance:9100\"}[$__rate_interval]) ",
     "legendFormat": "Cpu - {{cpu}}"
    }
   ]
  },
  {
   "title": "Top Containers on Node",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, sum by (pod, container)(rate(container_cpu_usage_seconds_total{image!=\"\", instance=\"$instance:10250\"}[$__rate_interval])))",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "Throttled Seconds",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk( 3, sum by (id,pod,container)(rate(container_cpu_cfs_throttled_seconds_total{instance=\"$instance:10250\", container=\"\"}[$__rate_interval])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Advanced PSI enabled",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true
  }
 ]
}