{
 "title": "Scheduler",
 "tags": [ "shancor" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(scheduler_e2e_scheduling_duration_seconds_bucket, job)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "scheduler pending pods",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance)(scheduler_pending_pods{job=\"$job\"})",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Schedule Attempts",
   "type": "stat",
   "description": "Count of attempts to schedule a pod, broken out by result",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance)(irate(scheduler_schedule_attempts_total{job=\"$job\"}[1m])) ",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"2..\"}[$__rate_interval])) ",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"3..\"}[2m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"$job\",code=~\"4..\"}[2m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(rest_client_requests_total{job=\"$job\",code=~\"5..\"}[2m])) ",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "client requests errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "max without(instance, method, host)(increase(rest_client_requests_total{job=\"$job\",code!~\"2..\"}[$__rate_interval]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Scheduling Duration",
   "type": "heatmap",
   "description": "Total elapsed latency in scheduling workload pods on worker node",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "max without(instance)(increase(scheduler_e2e_scheduling_duration_seconds_bucket{job=\"$job\", result=\"scheduled\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "max without(instance,verb,url)(increase(rest_client_request_duration_seconds_bucket{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}