{
 "title": "Prometheus Operator / Overview",
 "tags": [
  "prometheus",
  "prometheus-operator",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "job",
    "query": {
     "query": "label_values(prometheus_operator_build_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (prometheus_operator_build_info{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_rule_validation_errors_total{job=\"$job\"}",
     "legendFormat": "Rules validation errors"
    }
   ]
  },
  {
   "title": "List Operations failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_list_operations_failed_total{job=\"$job\"}",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "title": "Watch Operations failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_watch_operations_failed_total{job=\"$job\"}",
     "legendFormat": "{{ controller }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\"}[1m])",
     "legendFormat": "CPU {{ container }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "Memory {{ container }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Prometheus Operator Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{app=\"prometheus-operator\"}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Selected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_managed_resources{state=\"selected\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_managed_resources{state=\"rejected\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Operator API QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(prometheus_operator_kubernetes_client_http_request_duration_seconds_count{job=\"$job\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Reconciliation QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (controller) (rate(prometheus_operator_reconcile_duration_seconds_count{job=\"$job\"}[5m]))",
     "legendFormat": "{{ controller }}"
    }
   ]
  }
 ]
}