{
 "title": "ArgoCD / Application / Overview",
 "description": "A dashboard that monitors ArgoCD with a focus on Application status. It is created using the [argo-cd-mixin](https://github.com/adinhodovic/argo-cd-mixin).",
 "tags": [
  "ci/cd",
  "argo-cd",
  "argo",
  "gitops"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(argocd_app_info{}, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\"}, dest_server)"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$cluster\"}, project)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(argocd_app_info{namespace=~\"$namespace\", job=~\"$job\", dest_server=~\"$cluster\", project=~\"$project\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary by Cluster, Project", "type": "row" },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, health_status)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, sync_status)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Syncs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n      }[$__rate_interval]\n    )\n  )\n) by (job, dest_server, project, phase)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Application Auto Sync Enabled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n  }\n) by (job, dest_server, project, autosync_enabled)\n",
     "legendFormat": "{{ dest_server }}/{{ project }} - {{ autosync_enabled }}"
    }
   ]
  },
  { "title": "Application Badges", "type": "text", "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 }, "options": { "content": "No applications defined" } },
  {
   "title": "Applications (Unhealthy/OutOfSync/AutoSyncDisabled) Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 18, "x": 0, "y": 11 }
  },
  {
   "title": "Applications Unhealthy",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n    health_status!~\"Healthy|Progressing\"\n  }\n) by (job, dest_server, project, name, health_status)\n"
    }
   ]
  },
  {
   "title": "Applications Out Of Sync",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n    sync_status!=\"Synced\"\n  }\n) by (job, dest_server, project, name, sync_status) > 0\n"
    }
   ]
  },
  {
   "title": "Applications That Failed to Sync[7d]",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n        phase!=\"Succeeded\"\n      }[7d]\n    )\n  )\n) by (job, dest_server, project, name, phase) > 0\n"
    }
   ]
  },
  {
   "title": "Applications With Auto Sync Disabled",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n    autosync_enabled!=\"true\"\n  }\n) by (job, dest_server, project, name, autosync_enabled) > 0\n"
    }
   ]
  },
  { "title": "Application ($application)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Application Health Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n    name=~\"$application\",\n  }\n) by (namespace, job, dest_server, project, name, health_status)\n",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ health_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  argocd_app_info{\n    namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n    name=~\"$application\",\n  }\n) by (namespace, job, dest_server, project, name, sync_status)\n",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ sync_status }}"
    }
   ]
  },
  {
   "title": "Application Sync Result",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  round(\n    increase(\n      argocd_app_sync_total{\n        namespace=~'$namespace',\njob=~'$job',\ndest_server=~'$cluster',\nproject=~'$project',\n\n        name=~\"$application\",\n      }[$__rate_interval]\n    )\n  )\n) by (namespace, job, dest_server, project, name, phase)\n",
     "legendFormat": "{{ dest_server }}/{{ project }}/{{ name }} - {{ phase }}"
    }
   ]
  }
 ]
}