{
 "title": "Portefaix / Applications / Health",
 "tags": [
  "logging",
  "prometheus",
  "loki",
  "observability",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "logs", "query": "loki" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "workload_type",
    "label": "Type",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\"},workload_type)"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{namespace=\"$namespace\", workload_type=\"$workload_type\"},workload)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log level",
    "query": {}
   },
   { "name": "query", "label": "Search Query word" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ds" },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\",service=\"$workload\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Deployment Health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=\"$workload\", job=\"kube-state-metrics\"}\n/\nkube_deployment_spec_replicas{namespace=\"$namespace\", deployment=\"$workload\", job=\"kube-state-metrics\"}\nor\nkube_daemonset_status_number_ready{namespace=\"$namespace\", daemonset=\"$workload\", job=\"kube-state-metrics\"}\n/\nkube_daemonset_status_desired_number_scheduled{namespace=\"$namespace\", daemonset=\"$workload\", job=\"kube-state-metrics\"}\nor\nkube_statefulset_status_replicas_ready{namespace=\"$namespace\", statefulset=\"$workload\", job=\"kube-state-metrics\"}\n/\nkube_statefulset_status_replicas{namespace=\"$namespace\", statefulset=\"$workload\", job=\"kube-state-metrics\"}",
     "legendFormat": "{{ deployment }} {{ daemonset }} {{ statefulset }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total logs by time / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", job=~\"$app\", container=~\"$container\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "title": "Total log by level / $__interval",
   "type": "timeseries",
   "description": "level percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$app\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval]))"
    }
   ]
  },
  {
   "title": "total log line by app / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", job=~\"$app\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval])) by (app)"
    }
   ]
  }
 ]
}