{
 "title": "Portefaix / Applications / Logs",
 "tags": [
  "logging",
  "loki",
  "observability",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "component",
    "label": "Component",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   },
   { "name": "query", "label": "Search Query word" },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "ds" },
  {
   "title": "Total logs by time / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval]))",
     "legendFormat": "Log count"
    }
   ]
  },
  {
   "title": "Total log by level / $__interval",
   "type": "timeseries",
   "description": "level percentile",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({app=~\"$app\", namespace=~\"$namespace\", component=~\"$component\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval]))"
    }
   ]
  },
  {
   "title": "total log line by app / $__interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=~\"$app\", namespace=~\"$namespace\", component=~\"$component\", level=~\"$level\"} |~ \"(?i)$query\" [$__interval])) by (app)"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"(?i)error\"} | __error__=\"\" [$interval]))"
    }
   ]
  },
  {
   "title": "WARNING",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"(?i)warn.*\"} | __error__=\"\" [$interval]))"
    }
   ]
  },
  {
   "title": "INFO",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"(?i)info\"} | __error__=\"\" [$interval]))"
    }
   ]
  },
  {
   "title": "DEBUG",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"(?i)debug\"} | __error__=\"\" [$interval]))"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"(?i)unknown\"} | __error__=\"\" [$interval]))"
    }
   ]
  },
  {
   "title": "ALL",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", component=~\"$component\", container=~\"$container\"} | __error__=\"\" [$interval]))"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Content",
   "type": "logs",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app =~\"$app\", component=~\"$component\", container=~\"$container\", level=~\"$level\"} |~ \"(?i)$query\""
    }
   ]
  }
 ]
}