{
 "title": "Portefaix / Logs / Overview",
 "tags": [
  "logging",
  "loki",
  "observability",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Logs", "label": "Logs", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repartition",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (count_over_time({namespace=~\".+\"} [5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace) (count_over_time({namespace=~\".+\"} [5m]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repartition",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app) (rate({app=~\".+\"}[5m]))",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Number of lines / 5m",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 15, "x": 9, "y": 13 },
     "targets": [
      {
       "expr": "topk(10,sum(rate({app=~\".+\"}[5m])) by (app))",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repartition",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 9, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (app) (count_over_time({app=~\".+\"} |= \"error\" [5m]))",
       "legendFormat": "{{app}}"
      }
     ]
    },
    {
     "title": "Number of errors / 5m",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 15, "x": 9, "y": 14 },
     "targets": [
      {
       "expr": "sum(count_over_time({app=~\".+\"} |= \"error\" [5m])) by (app)",
       "legendFormat": "{{app}}"
      }
     ]
    }
   ]
  }
 ]
}