{
 "title": "Memcached",
 "description": "Visualize memcached-exporter metrics",
 "tags": [
  "cache",
  "memcached",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(memcached_version,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(memcached_version{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (memcached_version{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_uptime_seconds{job=\"$job\"} and memcached_up{job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_uptime_seconds{job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum by (pod) (memcached_current_bytes{job=\"$job\"}/memcached_limit_bytes{job=\"$job\"})",
     "legendFormat": "{{pod}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Hit & Miss ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "  sum (rate(memcached_commands_total{job=\"$job\", command=\"get\", status=\"hit\"}[1m]))\n/ sum (rate(memcached_commands_total{job=\"$job\", command=\"get\"}[1m]))",
     "legendFormat": "hit"
    },
    {
     "expr": "  sum (rate(memcached_commands_total{job=\"$job\", command=\"get\", status=\"miss\"}[1m]))\n/ sum (rate(memcached_commands_total{job=\"$job\", command=\"get\"}[1m]))",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Get & Set ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{command=\"get\",job=\"$job\"}[1m]))\n/ \nsum(rate(memcached_commands_total{command=~\"get|set\",job=\"$job\"}[1m]))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(memcached_commands_total{command=\"set\",job=\"$job\"}[1m]))\n/\nsum(rate(memcached_commands_total{command=~\"get|set\",job=\"$job\"}[1m]))",
     "legendFormat": "set"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memcached Log",
     "type": "logs",
     "gridPos": { "h": 20, "w": 21, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{namespace=\"$namespace\", job=~\"$job\", app=~\"$app\"}"
      }
     ]
    },
    {
     "title": "Logs in ERROR",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$job\", app=~\"$app\", level=~\"error\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in WARN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$job\", app=~\"$app\", level=~\"warn.*\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in INFO",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$job\", app=~\"$app\", level=~\"info\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in DEBUG",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$job\", app=~\"$app\", level=~\"debug\"} [$__interval]))"
      }
     ]
    },
    {
     "title": "Logs in UNKNOWN",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", job=~\"$job\", app=~\"$app\", level=~\"unknown\"} [$__interval]))"
      }
     ]
    }
   ]
  },
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_current_bytes{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Items",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_current_items{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Evicts (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (memcached_items_evicted_total{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Reclaims (total)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(memcached_items_reclaimed_total{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Accepting",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (memcached_accepting_connections{job=\"$job\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Throttled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_connections_yielded_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Refused",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_connections_listener_disabled_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Too large",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_item_too_large_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "No Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(memcached_item_no_memory_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "memcached_current_connections{job=\"$job\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "memcached_current_connections{job=\"$job\"} / memcached_max_connections{job=\"$job\"}",
     "legendFormat": "% {{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{job=\"$job\"}[$__rate_interval]))/30",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Get Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{status=\"hit\",command=\"get\",job=\"$job\"}[$__rate_interval]))\n/\nsum(rate(memcached_commands_total{command=\"get\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Hit"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(memcached_read_bytes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "read {{ pod }}"
    },
    {
     "expr": "- sum by (pod) (rate(memcached_written_bytes_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "write {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memcached_current_bytes{job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "memcached_current_bytes{job=\"$job\"}\n/\nmemcached_limit_bytes{job=\"$job\"}",
     "legendFormat": "%{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(memcached_process_system_cpu_seconds_total{job=\"$job\"}[$__rate_interval]) + rate(memcached_process_user_cpu_seconds_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Evicts & Reclaims rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_items_evicted_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "evicts"
    },
    {
     "expr": "sum(rate(memcached_items_reclaimed_total{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "reclaims"
    }
   ]
  },
  {
   "title": "New Items",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(memcached_items_total{job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Items in cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "memcached_current_items{job=\"$job\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{job=\"$job\"}[$__rate_interval])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(memcached_commands_total{job=\"$job\", status=\"hit\"}[1m]))\n/\nsum(rate(memcached_commands_total{job=\"$job\"}[1m]))",
     "legendFormat": "Total Hit Ratio"
    },
    {
     "expr": "sum(rate(memcached_commands_total{status=\"hit\",command=\"get\",job=\"$job\"}[$__rate_interval]))\n/\nsum(rate(memcached_commands_total{command=\"get\",job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "Get Hit Ratio"
    }
   ]
  },
  {
   "title": "Hit Ratio Per Command",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (command) (rate(memcached_commands_total{job=\"$job\", status=\"hit\"}[1m]))\n/ sum by (command) (rate(memcached_commands_total{job=\"$job\"}[1m])) ",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}