{
 "title": "Portefaix / Redis / Overview",
 "description": "Portefaix / Redis / Overview",
 "tags": [
  "redis",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_Metrics", "label": "Metrics", "query": "prometheus" },
   { "name": "DS_Logs", "label": "Logs", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(redis_instance_info,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(redis_instance_info{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "label": "Log App",
    "query": {}
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (redis_version) (redis_instance_info{namespace=\"$namespace\", job=~\"$job\"})",
     "legendFormat": "Loki"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_db_keys{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Number of keys"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Connected clients"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_blocked_clients{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Blocked clients"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Loki Log",
   "type": "logs",
   "gridPos": { "h": 20, "w": 21, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=~\"$app\", level=~\"$level\"}"
    }
   ]
  },
  {
   "title": "Logs in ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"error\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in WARN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=~\"warn.*\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in INFO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"info\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in DEBUG",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"debug\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Logs in UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({namespace=~\"$namespace\", app=~\"$app\", level=\"unknown\"} [$__interval]))"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Used memory"
    },
    {
     "expr": "redis_memory_used_peak_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Used Memory Peak"
    },
    {
     "expr": "redis_memory_used_lua_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Used Memory Lua"
    },
    {
     "expr": "redis_memory_used_dataset_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Used Memory Dataset"
    },
    {
     "expr": "redis_memory_used_overhead_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Used Memory Overhead"
    },
    {
     "expr": "redis_memory_used_rss_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Used Memory RSS"
    }
   ]
  },
  {
   "title": "Keys",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_keyspace_hits_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "redis_keyspace_misses_total{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Ops/sec[3m]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(redis_commands_processed_total{namespace=\"$namespace\", job=\"$job\"}[3m])/180",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{namespace=\"$namespace\", job=\"$job\"}[2m])) by (cmd)\n  /\nsum(irate(redis_commands_total{namespace=\"$namespace\", job=\"$job\"}[2m])) by (cmd)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{namespace=\"$namespace\", job=\"$job\"}[2m])) by (cmd) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keys / DB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "redis_db_keys{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate(redis_expired_keys_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "Expired"
    },
    {
     "expr": "rate(redis_evicted_keys_total{namespace=\"$namespace\", job=\"$job\"}[5m])",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Commands / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_total{namespace=\"$namespace\", job=\"$job\"} [2m])) by (cmd) >1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{namespace=\"$namespace\", job=\"$job\"}[5m])) / sum(rate(redis_commands_processed_total{namespace=\"$namespace\", job=\"$job\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}