# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{- $cred := .Values.credentials }}
{{- $repoURL := .Values.git.repoURL }}
{{- range .Values.projects }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  labels:
    kargo.akuity.io/cred-type: git
  name: kargo-github-app
  namespace: {{ .name }}
spec:
  refreshInterval: {{ $cred.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $cred.secretStore }}
  target:
    creationPolicy: Owner
    name: kargo-github-app
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        githubAppID: "{{ `{{ .KARGO_GITHUB_APP_ID }}` }}"
        githubAppPrivateKey: "{{ `{{ .KARGO_GITHUB_APP_PRIVATE_KEY }}` }}"
        githubAppInstallationID: "{{ `{{ .KARGO_GITHUB_APP_INSTALLATION_ID }}` }}"
        repoURL: {{ $repoURL }}
        repoURLIsRegex: "false"
  data:
  - secretKey: KARGO_GITHUB_APP_ID
    remoteRef:
      key: KARGO_GITHUB_APP_ID
  - secretKey: KARGO_GITHUB_APP_INSTALLATION_ID
    remoteRef:
      key: KARGO_GITHUB_APP_INSTALLATION_ID
  - secretKey: KARGO_GITHUB_APP_PRIVATE_KEY
    remoteRef:
      key: KARGO_GITHUB_APP_PRIVATE_KEY
{{- end }}
