{
 "title": "Synology / Overview",
 "description": "A Dashboard for Synology NAS based on SNMP and Prometheus",
 "tags": [
  "synology",
  "dsm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Device",
    "query": {
     "query": "query_result(ssCpuUser{target=\"nas\"})"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(ifName{target=\"nas\",instance=\"$Device\"})"
    }
   },
   {
    "name": "raidName",
    "label": "Volume ID",
    "query": {
     "query": "query_result(raidName{target=\"nas\",instance=\"$Device\"})"
    }
   },
   {
    "name": "storageIODevice",
    "label": "Disk",
    "query": {
     "query": "query_result(storageIODevice{target=\"nas\",instance=\"$Device\"})"
    }
   },
   {
    "name": "spaceIODevice",
    "label": "Volume Name",
    "query": {
     "query": "query_result(spaceIODevice{target=\"nas\",instance=\"$Device\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sysUpTime{instance='$Device',target=\"nas\"}/100",
     "legendFormat": "uptime"
    },
    {
     "expr": "upgradeAvailable{instance='$Device',target=\"nas\"}"
    },
    {
     "expr": "temperature{target=\"nas\", instance='$Device'}"
    },
    {
     "expr": "cpuFanStatus{target=\"nas\",instance='$Device'}"
    },
    {
     "expr": "systemFanStatus{target=\"nas\",instance='$Device'}"
    },
    {
     "expr": "systemStatus{target=\"nas\",instance='$Device'}"
    },
    {
     "expr": "powerStatus{target=\"nas\",instance='$Device'}"
    }
   ]
  },
  { "title": "System State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ssCpuUser{target=\"nas\", instance='$Device'} + ssCpuSystem{target=\"nas\", instance='$Device'}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "laLoadInt{target=\"nas\",instance='$Device'}",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ssCpuSystem{instance='$Device',target='nas'}",
     "legendFormat": "System"
    },
    {
     "expr": "ssCpuUser{instance='$Device',target='nas'}",
     "legendFormat": "User"
    },
    {
     "expr": "ssCpuIdle{instance='$Device',target='nas'}",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "serviceUsers{instance='$Device',target=\"nas\"}"
    }
   ]
  },
  { "title": "System Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalReal{target=\"nas\", instance='$Device'} - (memAvailReal{target=\"nas\", instance='$Device'} + memCached{target=\"nas\", instance='$Device'} + memBuffer{target=\"nas\", instance='$Device'})) / memTotalReal{target=\"nas\", instance='$Device'}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{instance='$Device',target=\"nas\"} + memTotalSwap{instance='$Device',target=\"nas\"} - memTotalFree{instance='$Device',target=\"nas\"}",
     "legendFormat": "Used Virtual Memory"
    },
    {
     "expr": "memTotalFree{instance='$Device',target=\"nas\"}",
     "legendFormat": "Free Virtual Memory"
    },
    {
     "expr": "memTotalReal{instance='$Device',target=\"nas\"} + memTotalSwap{instance='$Device',target=\"nas\"}",
     "legendFormat": "Total Virtual Memory"
    }
   ]
  },
  {
   "title": "Physical Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalReal{instance='$Device',target=\"nas\"} - (memShared{instance='$Device',target=\"nas\"} + memCached{instance='$Device',target=\"nas\"} + memBuffer{instance='$Device',target=\"nas\"} + memAvailReal{instance='$Device',target=\"nas\"})",
     "legendFormat": "Reserved"
    },
    {
     "expr": "memAvailReal{instance='$Device',target=\"nas\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "memBuffer{instance='$Device',target=\"nas\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "memCached{instance='$Device',target=\"nas\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "memShared{instance='$Device',target=\"nas\"}",
     "legendFormat": "Shared"
    },
    {
     "expr": "memTotalReal{instance='$Device',target=\"nas\"} ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "memTotalSwap{instance='$Device',target=\"nas\"} - memAvailSwap{instance='$Device',target=\"nas\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "memAvailSwap{instance='$Device',target=\"nas\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "memTotalSwap{instance='$Device',target=\"nas\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$Device',target=\"nas\"}"
    },
    {
     "expr": "ifAdminStatus{instance='$Device',target=\"nas\"}"
    },
    {
     "expr": "ifConnectorPresent{instance='$Device',target=\"nas\"}"
    },
    {
     "expr": "ifSpeed{instance='$Device',job=\"nas\"}"
    },
    {
     "expr": "ifOperStatus{instance='$Device',job=\"nas\"}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "diskTemperature{target=\"nas\", instance='$Device'}"
    },
    {
     "expr": "diskType{target=\"nas\", instance='$Device'}"
    },
    {
     "expr": "diskStatus{target=\"nas\", instance='$Device'}"
    },
    {
     "expr": "diskModel{target=\"nas\", instance='$Device'}"
    }
   ]
  },
  { "title": "Volume $raidName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "raidName" },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raidStatus{target=\"nas\",instance='$Device',raidName='$raidName'}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "raidTotalSize{instance='$Device',target=\"nas\",raidName=~'$raidName'}",
     "legendFormat": "Total Size"
    },
    {
     "expr": "raidFreeSize{instance='$Device',target=\"nas\",raidName=~'$raidName'}",
     "legendFormat": "Free Size"
    }
   ]
  },
  { "title": "Volume $spaceIODevice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "spaceIODevice" },
  {
   "title": "Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(spaceIONReadX{instance='$Device',target=\"nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(spaceIONWrittenX{instance='$Device',target=\"nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Written Bytes"
    }
   ]
  },
  {
   "title": "Volume IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(spaceIOReads{instance='$Device',target=\"nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(spaceIOWrites{instance='$Device',target=\"nas\",spaceIODevice=~\"$spaceIODevice\"}[$__interval])",
     "legendFormat": "Written Bytes"
    }
   ]
  },
  { "title": "Device $storageIODevice", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "storageIODevice" },
  {
   "title": "Device Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(storageIONReadX{instance='$Device',target=\"nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "rate(storageIONWrittenX{instance='$Device',target=\"nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Written Bytes"
    }
   ]
  },
  {
   "title": "Device IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(storageIOReads{instance='$Device',target=\"nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Read IOPS"
    },
    {
     "expr": "irate(storageIOWrites{instance='$Device',target=\"nas\",storageIODevice=~'$storageIODevice'}[$__interval])",
     "legendFormat": "Write IOPS"
    }
   ]
  },
  { "title": "Networking ($Interface)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "Interface" },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifHCInOctets{target='nas',instance='$Device',ifName=~'$Interface'}[$__interval]) or rate(ifInOctets{target='snmp',instance='$Device',ifName=~'$Interface'}[$__interval]) ",
     "legendFormat": "$Interface In"
    },
    {
     "expr": "rate(ifHCOutOctets{target='nas',instance='$Device',ifName=~'$Interface'}[$__interval]) or rate(ifOutOctets{target='snmp',instance='$Device',ifName=~'$Interface'}[$__interval]) ",
     "legendFormat": "$Interface Out"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ifInDiscards{target='nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Discards In"
    },
    {
     "expr": "rate(ifInErrors{target='nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Errors In"
    },
    {
     "expr": "rate(ifOutDiscards{target='nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Discards Out"
    },
    {
     "expr": "rate(ifOutErrors{job='nas',instance='$Device',ifName=~'$Interface'}[$__interval])",
     "legendFormat": "Errors Out"
    }
   ]
  }
 ]
}