{
 "title": "Grafana Agent / Overview",
 "description": "Portefaix / Grafana Agent Overview",
 "tags": [
  "grafana-agent",
  "opentelemetry",
  "portefaix-observability",
  "portefaix"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(agent_component_controller_running_components,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(agent_build_info,job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (agent_build_info{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "Grafana Agent"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Uptime / {{ service }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"$namespace\", job=\"$job\"}[1m])",
     "legendFormat": "CPU {{ service }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", job=\"$job\"}",
     "legendFormat": "Memory {{ service }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Grafana Agent Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{app=~\"grafana-agent-.+\"}"
    }
   ]
  },
  { "title": "Components", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Running agents",
   "type": "stat",
   "description": "The number of Grafana Agent Flow instances whose metrics are being sent and reported.\n",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "agents" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(agent_component_controller_evaluating{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running components",
   "type": "stat",
   "description": "The number of running components across all running agents.\n",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "components" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_component_controller_running_components{namespace=\"$namespace\", job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components by health",
   "type": "bargauge",
   "description": "Breakdown of components by health across all running agents.\n\n* Healthy: components have been evaluated completely and are reporting themselves as healthy.\n* Unhealthy: Components either could not be evaluated or are reporting themselves as unhealthy.\n* Unknown: A component has been created but has not yet been started.\n* Exited: A component has exited. It will not return to the running state.\n\nMore information on a component's health state can be retrieved using\nthe Grafana Agent Flow UI.\n\nNote that components may be in a degraded state even if they report\nthemselves as healthy. Use component-specific dashboards and alerts\nto observe detailed information about the behavior of a component.\n",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(agent_component_controller_running_components{namespace=\"$namespace\", job=\"$job\", health_type=\"healthy\"}) or vector(0)",
     "legendFormat": "Healthy"
    },
    {
     "expr": "sum(agent_component_controller_running_components{namespace=\"$namespace\", job=\"$job\", health_type=\"unhealthy\"}) or vector(0)",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(agent_component_controller_running_components{namespace=\"$namespace\", job=\"$job\", health_type=\"unknown\"}) or vector(0)",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(agent_component_controller_running_components{namespace=\"$namespace\", job=\"$job\", health_type=\"exited\"}) or vector(0)",
     "legendFormat": "Exited"
    }
   ]
  },
  { "title": "Evaluation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Graph evaluation histogram",
   "type": "heatmap",
   "description": "Detailed histogram view of how long graph evaluations take.\n\nThe goal is to design your config so that evaluations take as little\ntime as possible; under 100ms is a good goal.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (le) (increase(agent_component_evaluation_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Graph evaluation rate",
   "type": "timeseries",
   "description": "The frequency in which the component graph gets updated.\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(agent_component_evaluation_seconds_count{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph evaluation time",
   "type": "timeseries",
   "description": "The percentiles for how long it takes to complete a graph evaluation.\n\nGraph evaluations must complete for components to have the latest\narguments. The longer graph evaluations take, the slower it will be to\nreconcile the state of components.\n\nIf evaluation is taking too long, consider sharding your components to\ndeal with smaller amounts of data and reuse data as much as possible.\n",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(agent_component_evaluation_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(agent_component_evaluation_seconds_bucket{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "sum(rate(agent_component_evaluation_seconds_sum{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval])) /\nsum(rate(agent_component_evaluation_seconds_count{namespace=\"$namespace\", job=\"$job\"}[$__rate_interval]))\n",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}