# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

{{ if .Values.ack.enabled -}}
---
apiVersion: eks.services.k8s.aws/v1alpha1
kind: PodIdentityAssociation
metadata:
  name: {{ .Values.ack.clusterName }}-pyroscope
  namespace: {{ .Release.Namespace }}
spec:
  clusterName: {{ .Values.ack.clusterName }}
  namespace: {{ .Release.Namespace }}
  serviceAccount: {{ .Values.ack.serviceAccount }}
  roleRef:
    name: {{ .Values.ack.clusterName }}-pyroscope
  tags:
    {{- toYaml .Values.ack.tags | nindent 4 }}
{{- end }}
