{
 "title": "Spice.ai / Overview",
 "tags": [
  "data-cdn",
  "spiceai"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pods",
    "label": "Pods",
    "query": {
     "query": "label_values(runtime_flight_server_started,pod)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "50th : 0.5, 75th : 0.75, 90th : 0.9, 95th : 0.95, 99th : 0.99"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Spiced",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(runtime_flight_server_started)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Spice Health",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(pod) (count_over_time(runtime_flight_server_started[$__range])) * 10000) / $__range_ms * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Datasets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "dataset_active_count{pod=~\"${pods}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Models",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "model_active_count{pod=~\"${pods}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "SQL Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (protocol, quantile)(query_duration_ms_summary{quantile=~\"${percentile}\",pod=~\"${pods}\"}>0)",
     "legendFormat": "{{protocol}} (P{{quantile}})"
    }
   ]
  },
  {
   "title": "Query Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (err_code) ((query_failures{pod=~\"${pods}\"} - (query_failures{pod=~\"${pods}\"} offset $__rate_interval))>0)",
     "legendFormat": "{{err_code}}"
    }
   ]
  },
  { "title": "Accelerated Datasets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Time Since Last Refresh",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1000*time()-dataset_acceleration_last_refresh_time_ms{pod=~\"${pods}\",dataset!~\"runtime.*\"}",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  {
   "title": "Refresh Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (dataset) ((dataset_acceleration_refresh_errors{pod=~\"${pods}\"}) - (dataset_acceleration_refresh_errors{pod=~\"${pods}\"} offset $__rate_interval)>0)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Federated Datasets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Time Since Offline",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sgn(dataset_unavailable_time_ms{pod=~\"${pods}\"})*(time()-dataset_unavailable_time_ms{pod=~\"${pods}\"})",
     "legendFormat": "{{dataset}}"
    }
   ]
  },
  { "title": "Results Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*sum(increase(results_cache_hits{pod=~\"${pods}\"}[$__rate_interval]))/sum(increase(results_cache_requests{pod=~\"${pods}\"}[$__rate_interval]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "100*(1-sum(increase(results_cache_hits{pod=~\"${pods}\"}[$__rate_interval]))/sum(increase(results_cache_requests{pod=~\"${pods}\"}[$__rate_interval])))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Cache Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(results_cache_request{pod=~\"${pods}\"}[$__rate_interval])) > 0",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(increase(results_cache_hits{pod=~\"${pods}\"}[$__rate_interval])) > 0",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "Cached Items Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "results_cache_items_count{pod=~\"${pods}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "results_cache_max_size_bytes{pod=~\"${pods}\"}",
     "legendFormat": "Available {{pod}}"
    },
    {
     "expr": "results_cache_size_bytes{pod=~\"${pods}\"}",
     "legendFormat": "Used {{pod}}"
    }
   ]
  },
  { "title": "Latency Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Operation Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (method, path, job, status, quantile) (http_requests_duration_ms_summary{quantile=~\"${percentile}\",pod=~\"${pods}\"} > 0)",
     "legendFormat": "{{method}} {{path}} (P{{quantile}})"
    }
   ]
  },
  {
   "title": "Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum by (path, method) (\n  http_requests_duration_ms_count{pod=~\"${pods}\"} - \n  http_requests_duration_ms_count{pod=~\"${pods}\"} offset $__rate_interval\n) > 0",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "Load Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Load Dataset Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dataset_acceleration_refresh_duration_ms_summary{quantile=~\"${percentile}\", pod=~\"${pods}\"} unless load_dataset == 0",
     "legendFormat": "{{dataset}} (P{{quantile}})"
    }
   ]
  },
  {
   "title": "Load Model Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "expr": "1000*model_load_duration_ms_summary{quantile=~\"${percentile}\", pod=~\"${pods}\"} unless model_load_duration_ms == 0",
     "legendFormat": "{{model}} (P{{quantile}})"
    }
   ]
  },
  {
   "title": "Secrets Load Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "secrets_store_load_duration_ms_summary{quantile=~\"${percentile}\", pod=~\"${pods}\"} unless secrets_store_load_duration_ms_summary == 0",
     "legendFormat": "P{{quantile}}"
    }
   ]
  },
  { "title": "Flight Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "do_put Flight Duration (by dataset)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flight_request_duration_ms_summary{quantile=~\"${percentile}\",pod=~\"${pods}\",method=\"do_put\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "do_put Flight Count (by dataset)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "(flight_requests{pod=~\"${pods}\",method=\"do_put\"} - (flight_requests{pod=~\"${pods}\",method=\"do_put\"} offset $__rate_interval)) > 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "do_get Flight Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flight_request_duration_ms_summary{quantile=~\"${percentile}\",pod=~\"${pods}\",method=\"do_get\"} unless flight_request_duration_ms_summary == 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "do_get Flight Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "(flight_requests{pod=~\"${pods}\",method=\"do_get\"} - (flight_requests{pod=~\"${pods}\",method=\"do_get\"} offset $__rate_interval)) > 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "get_flight_info Flight Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "flight_request_duration_ms_summary{quantile=~\"${percentile}\",pod=~\"${pods}\",method=\"get_flight_info\" } unless flight_request_duration_ms_summary == 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "get_flight_info Flight Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(flight_requests{pod=~\"${pods}\",method=\"get_flight_info\"} - (flight_requests{pod=~\"${pods}\",method=\"get_flight_info\"} offset $__rate_interval)) > 0",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Flight Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(flight_requests[$__rate_interval])",
     "legendFormat": "{{method}}/{{command}}"
    }
   ]
  }
 ]
}