# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: loki-ack
description: A Helm chart for Loki AWS resources using ACK
type: application
version: 0.1.0
appVersion: "2.9.4"
