# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
clusterName: portefaix-aws-staging
namespace: logging
serviceAccount: loki
region: eu-west-1
accountID: "123456789012" # Update with your AWS Account ID

enableKMS: false

tags:
  portefaix.xyz/version: v0.54.0
  Made-By: ACK
