# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Projet / Rebase

on: # yamllint disable-line rule:truthy
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Monitor Actions
      uses: GitHubSecurityLab/actions-permissions/monitor@bf82d13b9b10051d224345ab9184f5ede0a94289 # v1.0.2-beta9
      with:
        config: ${{ vars.PERMISSIONS_CONFIG }}
    - name: Checkout the latest code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@b87d48154a87a85666003575337e27b8cd65f691 # 1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
